# Generated by Django 4.0 on 2021-12-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('screen', models.FloatField()),
                ('CPU', models.TextField()),
                ('memory', models.TextField()),
                ('price', models.FloatField()),
                ('pc_mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.pcmark')),
            ],
        ),
    ]
