# Generated by Django 4.0 on 2021-12-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcmodel',
            old_name='pc_mark_id',
            new_name='pc_mark',
        ),
    ]
